name: Auto Deploy

on:
  push:
    branches:
      - master

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Install dependencies
        run: yarn

      - name: Build
        run: yarn run build

      - name: Deploy
        uses: easingthemes/ssh-deploy@v4.1.10
        with:
            SSH_PRIVATE_KEY: ${{ secrets.SERVER_SSH_KEY }}
            REMOTE_HOST: ${{ secrets.USER_HOST }}
            REMOTE_USER: ${{ secrets.USER_NAME }}
            SOURCE: "/build/"
            ARGS: -rltgoDzvO --delete
            TARGET: /home/ubuntu/blog/build
